### ISSUE TITLE
error thrown

### ISSUE THREAD

**Issue by saddam7263** [gwen001/autoknoxss#1]
php autoknoxss.php -a "Mozilla Firefox " -c "sucuricp_tfca_*********" -s https://www.****.co/jobs/ 
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/autoknoxss/KnoxssRequest.php:167
Stack trace:
#0 /root/autoknoxss/AutoKnoxss.php(239): KnoxssRequest->extractNonce()
#1 /root/autoknoxss/autoknoxss.php(113): AutoKnoxss->init()
#2 {main}
  thrown in /root/autoknoxss/KnoxssRequest.php on line 167

**Comment by gwen001** [comment]
Hi,

Thank you for your nice message, I hope you're good too.

Like the error says, the function `curl_init()` doesn't exist on your system, you need to install the PHP extension `php-curl`.

Anyway I don't recommand to use this program because Knoxss is behind a firewall and it's impossible to perform massive test.

Thanks, bye.
